version: "3"

services:
  opengrok:
    container_name: grok
    image: opengrok/docker
    ports:
      - "38080:38080/tcp"
    environment:
      REINDEX: '120'
      INOTIFY: '1'
    # Volumes store your data between container upgrades
    volumes:
       - './src/:/grok/src/'   # source code
       - './data/:/grok/data/' # index and other things for source code
       - './log/:/grok/log/'   # index and other things for source code
       - './etc/:/grok/etc/'     # folder contains configuration files
volumes:
  etc:
    driver: local
